name: "📚 Documentation"
description: "문서 개선 요청"
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        문서 개선에 관심을 가져주셔서 감사합니다. 좋은 문서는 프로젝트의 성공에 매우 중요합니다.

  - type: dropdown
    attributes:
      label: 📑 문서 유형
      description: 개선이 필요한 문서 유형을 선택해 주세요.
      options:
        - README
        - API 문서
        - 튜토리얼
        - 코드 주석
        - 기술 문서
        - 기타 (아래에 상세히 기술해 주세요)
    validations:
      required: true

  - type: textarea
    attributes:
      label: 📄 현재 문서 상태
      description: 현재 문서의 문제점이나 개선이 필요한 부분을 설명해 주세요.
      placeholder: 현재 문서의 어떤 부분이 불명확하거나 부족한지 설명해 주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: ✨ 제안하는 개선 사항
      description: 어떻게 문서를 개선할 수 있을지 제안해 주세요.
      placeholder: 추가되거나 수정되어야 할 내용을 구체적으로 설명해 주세요.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 🔍 참고 자료
      description: 개선에 도움이 될 수 있는 참고 자료가 있다면 공유해 주세요.
      placeholder: 링크, 예시 또는 기타 참고할 만한 자료를 제공해 주세요.
    validations:
      required: false
